#!/usr/bin/env bash

xmonad_status() {
  cat /tmp/xmonad
}

clock() {
  echo $(date +"%T")
}

battery() {
  ~/.xmonad/battery
}

wifi() {
  wifi=$(iwgetid -r)
  [ ! -z "$wifi" ] && echo "wifi:$wifi "
}

{
  while true
  do
    output="%{l}$(xmonad_status)%{r}$(battery)%{F#2aa198}$(wifi)%{F-}$(clock) "
    echo "$output"
    sleep 0.2
  done
} | lemonbar \
  -f "Fantasque Sans Mono:size=14" \
  -u 18 \
  -B "#002b36"
